<?php
/* These are the key/value pairs to be accepted for the easpd_country
   field :

albanie|Albany
allemagne|Germany
autriche|Austria
belgique|Belgium
bielorussie|Belarus
bosnie|Bosnia
bulgarie|Bulgaria
croatie|Croatia
dannemark|Denmark
espagne|Spain
estonie|Estonia
finlande|Finland
france|France
grece|Greece
hongrie|Hungary
iceland|Iceland
ireland|Ireland
italie|Italy
lettonie|Latvia
lituanie|Lithuania
luxembourg|Luxembourg
macedoine|Macedonia
moldavie|Moldova
montenegro|Montenegro
norvege|Norway
paysBas|Holland
pologne|Poland
portugal|Portugal
republiqueTcheque|Czech Republic
roumanie|Romania
russie|Russia
serbie|Serbia
slovaquie|Slovakia
slovenie|Slovenia
suede|Sweden
suisse|Switzerland
turquie|Turkey
uk|UK
ukraine|Ukraine

*/

/**
 * implements hook_menu
 *
 * Creates a "map" page
 */
function easpd_map_menu () {

  $items['map'] = array(
    'page callback' => 'easpd_map_view',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * hook_menu's page callback
 *
 * Renders the "map" page
 */
function easpd_map_view () {

  $build['default_message'] = array(
    '#markup' => '<h1>hello</h1>',
  );
  return $build;
}

// the following doesn't work, and I don't wanna know why…

/**
 * Adds a country field to a content type
 *
 * inspired by node_add_body_field (https://api.drupal.org/api/drupal/modules!node!node.module/function/node_add_body_field/7)
 */
/* function easpd_add_country_field ($type) { */

/*   $field = field_info_field('field_easpd_country'); */
/*   $instance = field_info_instance('node', 'easpd_country', $type->type); */

/*   if (empty($field)) { */
/*     $field = array( */
/*       'field_name' => 'easpd_country', */
/*       'type' => 'list_text', */
/*       'settings' => array( */
/*         'label' => 'Country', */
/*         'settings' => array( */
/*           'allowed_values' => $EASPD_MAP_COUNTRIES, */
/*         ), */
/*       ), */
/*       'entity_types' => array('node'), */
/*     ); */
/*     $field = field_create_field($field); */
/*   } */

/*   return $instance; */
/* } */
