<?php

/**
 * implements hook_menu
 *
 * Creates a "groups" page
 */
function easpd_groups_page_menu () {

  $items['groups'] = array(
    'page callback' => 'easpd_groups_page_view',
    'access callback' => TRUE,
  );

  return $items;
}

function get_groups () {

  // SQL query
  $select = db_select('node', 'n')
    ->fields('n', array('nid', 'sticky', 'created'))
    ->condition('n.type', 'group');

  $nids  = $select->execute()->fetchCol();
  $nodes = node_load_multiple($nids);

  return $nodes;
}

function get_group_contents ($group_nid) {

  // SQL query
  $select = db_select('node', 'n')
    ->fields('n', array('nid', 'sticky', 'created'))
    ->condition('n.type', 'group_content');

  $nids  = $select->execute()->fetchCol();
  $nodes = node_load_multiple($nids);

  if ($group_nid) {
    $filtered = array();
    foreach ($nodes as $nid => $node) {
      if ($group_nid === intval($node->og_group_ref['und'][0]['target_id'], 10)) {
        $filtered[$nid] = $node;
      }
    }
    $nodes = $filtered;
  }

  return $nodes;
}

/**
 * hook_menu's page callback
 *
 * Renders the "groups" page
 */
function easpd_groups_page_view () {

  // handy variables
  global $base_url;
  $module_path = drupal_get_path('module', 'easpd_map');

  $groups = get_groups();

  foreach ($groups as $gid => $group) {
    $group->og_contents = get_group_contents($gid);
  }

  // Build page
  drupal_set_title(t("Your groups"));

  $build['default_message'] = array(
    '#markup' => theme('easpd_groups_page',
                       array(
                         'groups' => $groups,
                       )),
  );
  return $build;
}

/**
 * implements hook_theme
 *
 */
function easpd_groups_page_theme () {

  return array(
    'easpd_groups_page' => array(
      'template' => 'easpd_groups_page',
      'variables' => array(
        'groups' => NULL,
      ),
    ),
  );
}